plated/my_app/urls.py
from django.urls import path
from . import views


urlpatterns = [

   path('', views.Home.as_view(), name='home'),
   path('about/', views.about, name='about'),
   path('recipes/', views.recipe_index, name='recipe-index'),
   path('recipes/<int:recipe_id>/', views.recipe_detail, name='recipe-detail'),
   path('recipes/create/', views.RecipeCreate.as_view(), name='recipe-create'),
   path('recipes/<int:pk>/update/', views.RecipeUpdate.as_view(), name='recipe-update'),
   path('recipes/<int:pk>/delete/', views.RecipeDelete.as_view(), name='recipe-delete'),
   path('recipes/<int:recipe_id>/add_meal/', views.add_meal, name='add-meal'),
   path('comments/create/', views.CommentCreate.as_view(), name='comment-create'),
   path('comments/<int:pk>/', views.CommentDetail.as_view(), name='comment-detail'),
   path('comments/', views.CommentList.as_view(), name='comment-index'),
   path('comments/<int:pk>/update/', views.CommentUpdate.as_view(), name='comment-update'),
   path('comments/<int:pk>/delete/', views.CommentDelete.as_view(), name='comment-delete'),
   path('accounts/signup/', views.signup, name='signup'),





]

plated/plated/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),# Mount the app's routes at the root URL
]

plated/my_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

# Create your models here.
class Recipe(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    ingredients = models.TextField(max_length=250)
    instructions = models.TextField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
         return f'{self.title} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('recipe-detail', kwargs={'recipe_id': self.id})
    


class Meal(models.Model):
    date = models.DateField('Date Made')
    type = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )

    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_type_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']  

# Add the Toy model
class Comment(models.Model):
    name = models.CharField(max_length=100)
    content = models.TextField(max_length=250)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('comment-detail', kwargs={'pk': self.id})

plated/my_app/forms.py
from django import forms
from .models import Meal

class MealForm(forms.ModelForm):
    class Meta:
        model = Meal
        fields = ['date', 'type']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

plated/my_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.decorators import login_required# add these 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView

from .models import Recipe, Comment
from .forms import MealForm


class Home(LoginView):
    template_name = 'home.html'

def about(request):
  
    return render(request, 'about.html')

@login_required
def recipe_index(request):
    recipes = Recipe.objects.filter(user=request.user)
    return render(request, 'recipes/index.html', {'recipes': recipes})

@login_required
def recipe_detail(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    meal_form = MealForm()
    return render(request, 'recipes/detail.html', {
        'recipe': recipe, 'meal_form': meal_form
    })

class RecipeCreate(LoginRequiredMixin, CreateView):
    model = Recipe
    fields = ['title', 'description', 'ingredients', 'instructions']
    def form_valid(self, form):
        form.instance.user = self.request.user  
        return super().form_valid(form)


class RecipeUpdate(LoginRequiredMixin, UpdateView):
    model = Recipe
    # Let's disallow the renaming of a cat by excluding the name field!
    fields = ['Title', 'description', 'ingredients']

class RecipeDelete(LoginRequiredMixin, DeleteView):
    model = Recipe
    success_url = '/recipes/'

@login_required
def add_meal(request, recipe_id):
    form = MealForm(request.POST)
    if form.is_valid():
        new_meal = form.save(commit=False)
        new_meal.recipe_id = recipe_id
        new_meal.save()
    return redirect('recipe-detail', recipe_id=recipe_id)

class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = '__all__'

class CommentList(LoginRequiredMixin, ListView):
    model = Comment

class CommentDetail(LoginRequiredMixin, DetailView):
    model = Comment

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    fields = ['name', 'color']

class CommentDelete(LoginRequiredMixin, DeleteView):
    model = Comment
    success_url = '/comments/'

def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in
            login(request, user)
            return redirect('recipe-index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)
    # Same as: 
    # return render(
    #     request, 
    #     'signup.html',
    #     {'form': form, 'error_message': error_message}
    # )

plated/my_app/templates/about.html
{% extends 'base.html' %} 
{% block content %}
<h1>About PlateD</h1>
<hr />
<p class="page-content">
  I like long romantic walks down the produce aisle. Also, I am currently job
  seeking!
</p>
{% endblock %}

plated/my_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'images/Plated_logo.svg' %}" />
    <title>PlateD</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    {% block head %} 
    {% endblock %}
  </head>
  <body>
    <header>
        <div class="header-logo-container">
          <a href="/">
              <img src="{% static 'images/plated-logo-resized.svg' %}" alt="PlateD Logo" />
          </a>
        </div>
        
        <nav>
          <ul>
            {% if user.is_authenticated %}
            <li><a href="{% url 'recipe-index' %}">All Recipes</a></li>
            <li><a href="{% url 'comment-index' %}">All Comments</a></li>
            <li><a href="{% url 'recipe-create' %}">Add a Recipe</a></li>
            <li><a href="{% url 'comment-create' %}">Add a Comment</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li>
              <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Log out</button>
              </form>
            </li>
            {% else %}
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'home' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        </nav>
    </header>
    <main>
     {% block content %} 
     {% endblock %}
     </main>
  </body>
</html>

plated/my_app/templates/home.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/home.css' %}"
/>
{% endblock %} {% block content %}

<section class="logo-container">
  
</section>
{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %} {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}" />
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}

{% endblock %}

plated/my_app/templates/my_app/comment_confirm_delete.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Comment?</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'comment-detail' comment.id %}" class="btn secondary"> Cancel </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

plated/my_app/templates/my_app/comment_detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/comments/comment-detail.css' %}" />
{% endblock %} 
{% block content %}

<div class="card" style="border-color: {{ comment.color }}">
  <div class="card-bg" style="background-color: {{ comment.color }}"></div>
  <div class="card-content">
    <h2>{{ comment.name }}</h2>
    <p>A {{ comment.color }} comment</p>
  </div>
</div>
<a href="{% url 'comment-update' comment.id %}" class="btn warn">Edit</a>
<a href="{% url 'comment-delete' comment.id %}" class="btn danger">Delete</a>


{% endblock %}

plated/my_app/templates/my_app/comment_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>Edit {{object.name}}</h1>
    {% else %}
      <h1>Add a Comment</h1>
    {% endif %}
    <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
  </div>
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>

{% endblock %}

plated/my_app/templates/my_app/comment_list.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/comments/comment-index.css' %}" />
{% endblock %} 
{% block content %}

<section class="page-header">
  <h1>All Cat Toys</h1>
  <img src="{% static 'images/string.svg' %}" alt="A ball of string" />
  <img src="{% static 'images/mouse.svg' %}" alt="A mouse" />
  <img src="{% static 'images/post.svg' %}" alt="A scratching post" />
  <img src="{% static 'images/fish.svg' %}" alt="A fishy toy" />
</section>

<section class="card-container">
  {% for comment in comment_list %}
    <div class="card" style="border-color: {{ comment.color }}">
      <div class="card-bg" style="background-color: {{ comment.color }}"></div>
      <a href="{% url 'comment-detail' comment.id %}">
        <div class="card-content">
          <h2>{{ comment.name }}</h2>
          <p>A {{ comment.color }} comment</p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

plated/my_app/templates/my_app/recipe_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Recipe?</h1>
  <img src="{% static 'images/ingredients.svg'%}" alt="A group of food ingredients" />
</div>

<h2>Are you sure you want to delete {{ recipe.title }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'recipe-detail' recipe.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

plated/my_app/templates/my_app/recipe_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}

  <div class="page-header">
  
    {% if recipe %}
      <h1>Edit {{ recipe.title }}</h1>
    {% else %}
      <h1>Add a Recipe</h1>
    {% endif %}
  <img src="{% static 'images/ingredients.svg' %}" alt="A group of foods" />
</div>

<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

plated/my_app/templates/recipes/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/recipes/recipe-details.css' %}" />
{% endblock %} 
{% block content %}
<section class="cat-container">
  <div class="cat-img">
    <img src="{% static 'images/recipe.svg' %}" alt="A Recipe book" />
  </div>
  <div class="cat-details">
    <h1>{{ recipe.title }}</h1>
    <p>{{ recipe.description }}</p>
    <div class="cat-actions">
        <a href="{% url 'recipe-update' recipe.id %}" class="btn warn">Edit</a>
        <a href="{% url 'recipe-delete' recipe.id %}" class="btn danger">Delete</a>
      </div>
  </div>
</section>
<!-- Existing cat-container above -->
<div class="feedings-toy-container">
  <section class="feedings">
    <div class="subsection-title">
      <h2>Made Recipe</h2>
      <img
        src="{% static 'images/cat-cone.svg' %}"
        alt="An ice cream cone cat"
      />
      <img src="{% static 'images/cat-onigiri.svg' %}" alt="A cat as onigiri" />
      <img
        src="{% static 'images/kitty-kabob.svg' %}"
        alt="A kabob of kittens"
      />
    </div>
    <h3>Add a Feeding</h3>
    <form
      action="{% url 'add-meal' recipe.id %}"
      method="post"
      class="subsection-content"
      autocomplete="off"
    >
      {% csrf_token %} 
      {{ meal_form.as_p }}
      <button type="submit" class="btn submit">Add Entry </button>
    </form>
    <h3>Past Meals</h3>
{% if recipe.meal_set.all.count %}
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Type</th>
        </tr>
      </thead>
      <tbody>
        {% for meal in recipe.meal_set.all %}
          <tr>
            <td>{{meal.date}}</td>
            <td>{{meal.get_type_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
  <div class="subsection-content">
    <p>⚠️ {{cat.name}} has not been fed!</p>
  </div>
{% endif %}
  </section>
</div>

{% endblock %}

plated/my_app/templates/recipes/index.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/recipes/recipe-index.css' %}"
/>
{% endblock %} {% block content %}

<section class="page-header">
  <h1>Recipe List</h1>
  <img
    src="{% static 'images/food_items.svg' %}"
    alt="A group of veggies"
  />
</section>

<section class="card-container">
    {% for recipe in recipes %}
      <div class="card">
        <a href="{% url 'recipe-detail' recipe.id %}">
          <div class="card-content">
            <div class="card-img-container">
              <img
                src="{% static 'images/recipe.svg' %}"
                alt="A recipe book"
              />
            </div>
            <h2 class="card-title">{{ recipe.title }}</h2>
            <p><small>{{ recipe.description }}</small></p>
          </div>
        </a>
      </div>
    {% endfor %}
  </section>

{% endblock %}

plated/my_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}